### ISSUE TITLE
Support for Athena query federation

### ISSUE THREAD

**Issue by applike-ss** [laughingman7743/PyAthena#394] opened 2022-12-22 07:16 UTC
Hello,

i don't know whether this is actually already supported or whether this will be a feature request.
I have tried to add an athena datasource to my superset instance which worked flawlessly when using the awsdatacatalog.
When using a data catalog with data source type "Data source connector" it does work in a way that i can connect.
However when trying to create a dataset (which is doing a athena.ListTableMetadata), i do not get any tables shown.
My assumption is that pyathena might be opinionated either when it comes to data types (i'm using a mysql that is queried by athena) or that the data structure is different when using a data source connector.
What i've seen from checking the output of superset is that the data types are db engine native types (e.g. varchar for mysql, which should be string as the equivalent for the awsdatacatalog).
Also these properties are missing per table when using federated queries with mysql:
* `CreateTime`
* `LastAccessTime`
* `Parameters`

I'd love to see federated queries supported if they aren't already or to hear what i'm doing wrong.

**Comment by laughingman7743** [comment] 2022-12-22 09:59
I'm not sure what the problem is, is it that you can't execute a federated query in Superset? Are you getting any errors?

> Also these properties are missing per table when using federated queries with mysql:
>
>     CreateTime
>     LastAccessTime
>     Parameters
Is the missing property a case of running the query using PyAthena? Are you saying that you cannot run federated queries with Superset, but you can run federated queries with PyAthena?

**Comment by applike-ss** [comment] 2022-12-22 10:03
> I'm not sure what the problem is, is it that you can't execute a federated query in Superset? Are you getting any errors?
> 
> > Also these properties are missing per table when using federated queries with mysql:
> > ```
> > CreateTime
> > LastAccessTime
> > Parameters
> > ```
> 
> Is the missing property a case of running the query using PyAthena? Are you saying that you cannot run federated queries with Superset, but you can run federated queries with PyAthena?

I can't create a dataset in superset with pyathena as query adapter. That is because after selecting the catalog and the database, the table dropdown loads and then finishes with no data. There are no errors.

the missing property must be related to the datasource being a data source connector, as the api call done is a `athena.ListTableMetadata` not a real query.

**Comment by applike-ss** [comment] 2022-12-22 10:04
I also created this issue on supersets side yesterday, as my first guess was that superset was not capable of federated queries with athena. that is until it came to my mind that the functionality of querying is abstracted away and in fact the query adapter (pyathena) likely has to support this instead.

ref: https://github.com/apache/superset/issues/22487

**Comment by laughingman7743** [comment] 2022-12-22 10:23
I am not sure about the Superset settings, do you have a setting for the catalog to be used? By default, awsdatacatalog is used.

**Comment by applike-ss** [comment] 2023-01-02 09:13
Yes, one can set `&catalog_name=foo` at the end of the sqlalchemy_uri

**Comment by laughingman7743** [comment] 2023-01-02 14:41
Yes, the catalog should be able to be specified in the connection string that way. I'll have to create a query federation environment and try this library to know better. I will try it soon.

**Comment by laughingman7743** [comment] 2023-02-04 06:00
The following changes may be related.
https://github.com/laughingman7743/PyAthena/pull/403

This change is included in v2.21.0, so please try v2.21.0.
https://github.com/laughingman7743/PyAthena/releases/tag/v2.21.0
https://pypi.org/project/pyathena/2.21.0/

**Comment by applike-ss** [comment] 2023-02-06 10:55
i will, as soon as it is included in apache superset. Thank you!

**Comment by laughingman7743** [comment] 2023-02-27 12:24
https://github.com/apache/superset/issues/22487#issuecomment-1429271737
The connection with Superset seems to be OK, so I will close this issue. If there is another problem, please create a new issue.

**Closed by laughingman7743** 2023-02-27 12:24 UTC
